github_url: https://github.com/ucsb-cs16-s18/ucsb-cs16-s18.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048

start_week: 1
start_date: 2018-04-01 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

instructor_url: https://ucsb-cs16.github.io/instructor

cal_dates: >
  [
  {"label":"First day of classes", "date":"2018-04-03" },
  {"label":"Univ Holiday", "date":"2018-05-28" },
  {"label":"Last day of classes", "date":"2018-06-08" }
  ]

course: "CS16"
legacy_wiki_name: 16wiki
legacy_wiki_url: "https://foo.cs.ucsb.edu/16wiki" 
qtr: "S18"
quarter: "Spring 2018 (Matni)"

kramdown:
   parse_block_html: true


exclude:
   - vendor

timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


